services:
  - type: web
    name: synctalk
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
        placeholder: "Enter your MongoDB Atlas Connection String (e.g. mongodb+srv://...)"
      - key: REDIS_URI
        fromRedis:
          name: synctalk-redis
          property: connectionString

redis:
  - name: synctalk-redis
    plan: free
